name: marketlens
version: 1.0.0
config-version: 2

profile: marketlens

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  marketlens:
    +materialized: view
    staging:
      +tags: ["staging"]
    marts:
      +tags: ["marts"]
      prices:
        +tags: ["marts", "prices"]
      macro:
        +tags: ["marts", "macro"]
      sec:
        +tags: ["marts", "sec"]
