{{ config(alias='V_CPI_CHANGES') }}

SELECT
    DATE,
    CPI_INDEX,
    LAG(CPI_INDEX) OVER (ORDER BY DATE) AS PREV_CPI,
    (CPI_INDEX - LAG(CPI_INDEX) OVER (ORDER BY DATE))
        / NULLIF(LAG(CPI_INDEX) OVER (ORDER BY DATE), 0) AS CPI_MOM_CHANGE
FROM {{ ref('stg_cpi') }}
WHERE CPI_INDEX IS NOT NULL
