{{ config(alias='V_FED_RATE_CHANGES') }}

SELECT
    DATE,
    FED_FUNDS_RATE,
    LAG(FED_FUNDS_RATE) OVER (ORDER BY DATE) AS PREV_RATE,
    FED_FUNDS_RATE - LAG(FED_FUNDS_RATE) OVER (ORDER BY DATE) AS RATE_CHANGE
FROM {{ ref('stg_fed_funds') }}
WHERE FED_FUNDS_RATE IS NOT NULL
