{{ config(alias='V_YIELD_CURVE_SIGNALS') }}

-- Flags dates where the inversion status flips.
SELECT
    DATE,
    CURVE_SPREAD,
    IS_INVERTED,
    LAG(IS_INVERTED) OVER (ORDER BY DATE) AS PREV_INVERTED,
    CASE
        WHEN IS_INVERTED = TRUE  AND LAG(IS_INVERTED) OVER (ORDER BY DATE) = FALSE THEN 'INVERSION_START'
        WHEN IS_INVERTED = FALSE AND LAG(IS_INVERTED) OVER (ORDER BY DATE) = TRUE  THEN 'INVERSION_END'
        ELSE NULL
    END AS FLIP_EVENT
FROM {{ ref('yield_curve') }}
QUALIFY FLIP_EVENT IS NOT NULL
