USE SCHEMA SCORPION_DB.MARKETLENS;

CREATE OR REPLACE VIEW V_DAILY_RETURNS AS
SELECT
    TICKER,
    DATE,
    CLOSE_PRICE,
    LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY DATE) AS PREV_CLOSE,
    (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY DATE))
        / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY DATE), 0) AS DAILY_RETURN
FROM V_STOCK_PRICES
WHERE CLOSE_PRICE IS NOT NULL;
