USE SCHEMA SCORPION_DB.MARKETLENS;

CREATE OR REPLACE VIEW V_ROLLING_VOLATILITY AS
SELECT
    TICKER,
    DATE,
    DAILY_RETURN,
    AVG(DAILY_RETURN) OVER (
        PARTITION BY TICKER ORDER BY DATE ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING
    ) AS AVG_RETURN_20D,
    STDDEV(DAILY_RETURN) OVER (
        PARTITION BY TICKER ORDER BY DATE ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING
    ) AS VOLATILITY_20D
FROM V_DAILY_RETURNS
WHERE DAILY_RETURN IS NOT NULL;
