USE SCHEMA SCORPION_DB.MARKETLENS;

CREATE OR REPLACE VIEW V_ANOMALY_SCORES AS
SELECT
    TICKER,
    DATE,
    DAILY_RETURN,
    AVG_RETURN_20D,
    VOLATILITY_20D,
    CASE
        WHEN VOLATILITY_20D > 0
        THEN (DAILY_RETURN - AVG_RETURN_20D) / VOLATILITY_20D
        ELSE 0
    END AS Z_SCORE,
    CASE
        WHEN ABS((DAILY_RETURN - AVG_RETURN_20D) / NULLIF(VOLATILITY_20D, 0)) > 2.0
        THEN TRUE
        ELSE FALSE
    END AS IS_ANOMALY
FROM V_ROLLING_VOLATILITY
WHERE VOLATILITY_20D IS NOT NULL;
