USE SCHEMA SCORPION_DB.MARKETLENS;

-- Fed Funds Rate: detect day-over-day changes
CREATE OR REPLACE VIEW V_FED_RATE_CHANGES AS
SELECT
    DATE,
    FED_FUNDS_RATE,
    LAG(FED_FUNDS_RATE) OVER (ORDER BY DATE) AS PREV_RATE,
    FED_FUNDS_RATE - LAG(FED_FUNDS_RATE) OVER (ORDER BY DATE) AS RATE_CHANGE
FROM V_FED_FUNDS_RATE
WHERE FED_FUNDS_RATE IS NOT NULL;

-- CPI: detect month-over-month changes
CREATE OR REPLACE VIEW V_CPI_CHANGES AS
SELECT
    DATE,
    CPI_INDEX,
    LAG(CPI_INDEX) OVER (ORDER BY DATE) AS PREV_CPI,
    (CPI_INDEX - LAG(CPI_INDEX) OVER (ORDER BY DATE))
        / NULLIF(LAG(CPI_INDEX) OVER (ORDER BY DATE), 0) AS CPI_MOM_CHANGE
FROM V_CPI
WHERE CPI_INDEX IS NOT NULL;
