USE SCHEMA SCORPION_DB.MARKETLENS;

CREATE OR REPLACE VIEW V_SIGNAL_SUMMARY AS

-- Stock anomalies
SELECT
    DATE,
    'STOCK_ANOMALY' AS SIGNAL_TYPE,
    TICKER AS ENTITY,
    ROUND(DAILY_RETURN * 100, 2) AS MAGNITUDE,
    ROUND(Z_SCORE, 2) AS SALIENCE_SCORE,
    TICKER || ' moved ' || ROUND(DAILY_RETURN * 100, 2) || '% (z-score: '
        || ROUND(Z_SCORE, 2) || ')' AS SUMMARY
FROM V_ANOMALY_SCORES
WHERE IS_ANOMALY = TRUE

UNION ALL

-- Fed rate changes (non-zero only)
SELECT
    DATE,
    'FED_RATE_CHANGE' AS SIGNAL_TYPE,
    'FED_FUNDS' AS ENTITY,
    ROUND(RATE_CHANGE * 10000, 1) AS MAGNITUDE,
    ABS(RATE_CHANGE) * 10000 AS SALIENCE_SCORE,
    'Fed Funds Rate changed by ' || ROUND(RATE_CHANGE * 10000, 1)
        || ' bps to ' || ROUND(FED_FUNDS_RATE * 100, 2) || '%' AS SUMMARY
FROM V_FED_RATE_CHANGES
WHERE ABS(RATE_CHANGE) > 0.0001

UNION ALL

-- CPI month-over-month changes (> 0.3% as notable)
SELECT
    DATE,
    'CPI_CHANGE' AS SIGNAL_TYPE,
    'CPI_ALL_ITEMS' AS ENTITY,
    ROUND(CPI_MOM_CHANGE * 100, 3) AS MAGNITUDE,
    ABS(CPI_MOM_CHANGE) * 1000 AS SALIENCE_SCORE,
    'CPI changed ' || ROUND(CPI_MOM_CHANGE * 100, 3)
        || '% month-over-month to ' || ROUND(CPI_INDEX, 2) AS SUMMARY
FROM V_CPI_CHANGES
WHERE ABS(CPI_MOM_CHANGE) > 0.003

UNION ALL

-- SEC filings (narrative signals, one row per latest 10-K/10-Q per ticker)
SELECT
    FILING_DATE AS DATE,
    'SEC_FILING' AS SIGNAL_TYPE,
    TICKER AS ENTITY,
    NULL AS MAGNITUDE,
    CASE UPPER(COALESCE(MANAGEMENT_TONE, ''))
        WHEN 'NEGATIVE' THEN 2.5
        WHEN 'CAUTIOUS' THEN 1.5
        WHEN 'POSITIVE' THEN 1.0
        ELSE 0.5
    END AS SALIENCE_SCORE,
    TICKER || ' filed ' || FORM_TYPE || ' (tone: '
        || COALESCE(MANAGEMENT_TONE, 'unknown') || ')' AS SUMMARY
FROM SCORPION_DB.MARKETLENS.V_SEC_NARRATIVES
WHERE FILING_DATE IS NOT NULL

UNION ALL

-- RSI extremes (overbought / oversold)
SELECT
    DATE,
    'RSI_EXTREME' AS SIGNAL_TYPE,
    TICKER AS ENTITY,
    ROUND(RSI_14, 2) AS MAGNITUDE,
    ROUND(ABS(RSI_14 - 50), 2) AS SALIENCE_SCORE,
    TICKER || ' RSI(14)=' || ROUND(RSI_14, 1) || ' (' || RSI_STATE || ')' AS SUMMARY
FROM V_RSI_14
WHERE RSI_STATE IN ('OVERBOUGHT', 'OVERSOLD')

UNION ALL

-- 50/200 SMA crossovers (golden / death)
SELECT
    DATE,
    'MA_CROSSOVER' AS SIGNAL_TYPE,
    TICKER AS ENTITY,
    ROUND(SMA_50 - SMA_200, 2) AS MAGNITUDE,
    CASE CROSSOVER_EVENT WHEN 'DEATH_CROSS' THEN 3.5 ELSE 3.0 END AS SALIENCE_SCORE,
    TICKER || ' ' || CROSSOVER_EVENT || ' (SMA50=' || ROUND(SMA_50, 2)
        || ', SMA200=' || ROUND(SMA_200, 2) || ')' AS SUMMARY
FROM V_MA_CROSSOVER
WHERE CROSSOVER_EVENT IS NOT NULL

UNION ALL

-- Drawdown from 52-week high (correction / bear)
SELECT
    DATE,
    'DRAWDOWN' AS SIGNAL_TYPE,
    TICKER AS ENTITY,
    ROUND(DRAWDOWN_PCT * 100, 2) AS MAGNITUDE,
    ROUND(ABS(DRAWDOWN_PCT) * 10, 2) AS SALIENCE_SCORE,
    TICKER || ' down ' || ROUND(DRAWDOWN_PCT * 100, 1)
        || '% from 52w high (' || DRAWDOWN_STATE || ')' AS SUMMARY
FROM V_DRAWDOWN
WHERE DRAWDOWN_STATE IS NOT NULL

UNION ALL

-- Sector rotation: top and bottom sector by 20-day return per day
SELECT
    r.DATE,
    'SECTOR_ROTATION' AS SIGNAL_TYPE,
    r.SECTOR AS ENTITY,
    ROUND(r.AVG_20D_RETURN * 100, 2) AS MAGNITUDE,
    ROUND(ABS(r.AVG_20D_RETURN) * 100, 2) AS SALIENCE_SCORE,
    r.SECTOR || CASE WHEN r.SECTOR_RANK = 1 THEN ' leading' ELSE ' lagging' END
        || ' sector: 20d avg return ' || ROUND(r.AVG_20D_RETURN * 100, 2) || '%' AS SUMMARY
FROM V_SECTOR_ROTATION r
JOIN (
    SELECT DATE, MAX(SECTOR_RANK) AS MAX_RANK FROM V_SECTOR_ROTATION GROUP BY DATE
) m ON m.DATE = r.DATE
WHERE r.SECTOR_RANK = 1 OR r.SECTOR_RANK = m.MAX_RANK;
