USE SCHEMA SCORPION_DB.MARKETLENS;

CREATE OR REPLACE VIEW V_SIGNAL_SUMMARY AS

-- Stock anomalies
SELECT
    DATE,
    'STOCK_ANOMALY' AS SIGNAL_TYPE,
    TICKER AS ENTITY,
    ROUND(DAILY_RETURN * 100, 2) AS MAGNITUDE,
    ROUND(Z_SCORE, 2) AS SALIENCE_SCORE,
    TICKER || ' moved ' || ROUND(DAILY_RETURN * 100, 2) || '% (z-score: '
        || ROUND(Z_SCORE, 2) || ')' AS SUMMARY
FROM V_ANOMALY_SCORES
WHERE IS_ANOMALY = TRUE

UNION ALL

-- Fed rate changes (non-zero only)
SELECT
    DATE,
    'FED_RATE_CHANGE' AS SIGNAL_TYPE,
    'FED_FUNDS' AS ENTITY,
    ROUND(RATE_CHANGE * 10000, 1) AS MAGNITUDE,
    ABS(RATE_CHANGE) * 10000 AS SALIENCE_SCORE,
    'Fed Funds Rate changed by ' || ROUND(RATE_CHANGE * 10000, 1)
        || ' bps to ' || ROUND(FED_FUNDS_RATE * 100, 2) || '%' AS SUMMARY
FROM V_FED_RATE_CHANGES
WHERE ABS(RATE_CHANGE) > 0.0001

UNION ALL

-- CPI month-over-month changes (> 0.3% as notable)
SELECT
    DATE,
    'CPI_CHANGE' AS SIGNAL_TYPE,
    'CPI_ALL_ITEMS' AS ENTITY,
    ROUND(CPI_MOM_CHANGE * 100, 3) AS MAGNITUDE,
    ABS(CPI_MOM_CHANGE) * 1000 AS SALIENCE_SCORE,
    'CPI changed ' || ROUND(CPI_MOM_CHANGE * 100, 3)
        || '% month-over-month to ' || ROUND(CPI_INDEX, 2) AS SUMMARY
FROM V_CPI_CHANGES
WHERE ABS(CPI_MOM_CHANGE) > 0.003

UNION ALL

-- SEC filings (narrative signals, one row per latest 10-K/10-Q per ticker)
SELECT
    FILING_DATE AS DATE,
    'SEC_FILING' AS SIGNAL_TYPE,
    TICKER AS ENTITY,
    NULL AS MAGNITUDE,
    CASE UPPER(COALESCE(MANAGEMENT_TONE, ''))
        WHEN 'NEGATIVE' THEN 2.5
        WHEN 'CAUTIOUS' THEN 1.5
        WHEN 'POSITIVE' THEN 1.0
        ELSE 0.5
    END AS SALIENCE_SCORE,
    TICKER || ' filed ' || FORM_TYPE || ' (tone: '
        || COALESCE(MANAGEMENT_TONE, 'unknown') || ')' AS SUMMARY
FROM SCORPION_DB.MARKETLENS.V_SEC_NARRATIVES
WHERE FILING_DATE IS NOT NULL;
