USE SCHEMA SCORPION_DB.MARKETLENS;

-- Latest filing per ticker, joined with metadata for serving.
CREATE OR REPLACE VIEW V_SEC_NARRATIVES AS
WITH RANKED AS (
    SELECT
        s.*,
        ROW_NUMBER() OVER (
            PARTITION BY s.TICKER, s.FORM_TYPE
            ORDER BY s.FILING_DATE DESC
        ) AS RN
    FROM SCORPION_DB.MARKETLENS.SEC_FILING_SUMMARIES s
)
SELECT
    TICKER,
    FORM_TYPE,
    FILING_DATE,
    ACCESSION_NUMBER,
    REVENUE_NARRATIVE,
    GUIDANCE_NARRATIVE,
    RISK_NARRATIVE,
    MANAGEMENT_TONE,
    EARNINGS_CONTEXT_SUMMARY,
    MODEL,
    SUMMARIZED_AT
FROM RANKED
WHERE RN = 1;
