{{ config(alias='V_ANOMALY_SCORES') }}

SELECT
    TICKER,
    DATE,
    DAILY_RETURN,
    AVG_RETURN_20D,
    VOLATILITY_20D,
    CASE
        WHEN VOLATILITY_20D > 0
        THEN (DAILY_RETURN - AVG_RETURN_20D) / VOLATILITY_20D
        ELSE 0
    END AS Z_SCORE,
    CASE
        WHEN ABS((DAILY_RETURN - AVG_RETURN_20D) / NULLIF(VOLATILITY_20D, 0)) > 2.0
        THEN TRUE
        ELSE FALSE
    END AS IS_ANOMALY
FROM {{ ref('rolling_volatility') }}
WHERE VOLATILITY_20D IS NOT NULL
