{{ config(alias='V_DAILY_RETURNS') }}

SELECT
    TICKER,
    DATE,
    CLOSE_PRICE,
    LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY DATE) AS PREV_CLOSE,
    (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY DATE))
        / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY DATE), 0) AS DAILY_RETURN
FROM {{ ref('stg_stock_prices') }}
WHERE CLOSE_PRICE IS NOT NULL
