{{ config(alias='V_MA_CROSSOVER') }}

WITH smas AS (
    SELECT
        TICKER,
        DATE,
        CLOSE_PRICE,
        AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY DATE ROWS BETWEEN 49  PRECEDING AND CURRENT ROW) AS SMA_50,
        AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY DATE ROWS BETWEEN 199 PRECEDING AND CURRENT ROW) AS SMA_200,
        COUNT(*)         OVER (PARTITION BY TICKER ORDER BY DATE ROWS BETWEEN 199 PRECEDING AND CURRENT ROW) AS WIN_N
    FROM {{ ref('stg_stock_prices') }}
),
flagged AS (
    SELECT
        TICKER, DATE, CLOSE_PRICE, SMA_50, SMA_200, WIN_N,
        LAG(SMA_50 - SMA_200) OVER (PARTITION BY TICKER ORDER BY DATE) AS PREV_DIFF,
        SMA_50 - SMA_200                                               AS CUR_DIFF
    FROM smas
)
SELECT
    TICKER,
    DATE,
    CLOSE_PRICE,
    SMA_50,
    SMA_200,
    CASE
        WHEN WIN_N < 200                             THEN NULL
        WHEN PREV_DIFF <= 0 AND CUR_DIFF > 0         THEN 'GOLDEN_CROSS'
        WHEN PREV_DIFF >= 0 AND CUR_DIFF < 0         THEN 'DEATH_CROSS'
        ELSE NULL
    END AS CROSSOVER_EVENT
FROM flagged
