{{ config(alias='V_ROLLING_VOLATILITY') }}

SELECT
    TICKER,
    DATE,
    DAILY_RETURN,
    AVG(DAILY_RETURN) OVER (
        PARTITION BY TICKER ORDER BY DATE ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING
    ) AS AVG_RETURN_20D,
    STDDEV(DAILY_RETURN) OVER (
        PARTITION BY TICKER ORDER BY DATE ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING
    ) AS VOLATILITY_20D
FROM {{ ref('daily_returns') }}
WHERE DAILY_RETURN IS NOT NULL
